### ISSUE TITLE
tidy object

### ISSUE THREAD

**Issue by rpietro** [muschellij2/fedreporter#1]
@muschellij2 outstanding package, very useful. I was able to print the list object (using sink), but am having a hard time converting it to a tidytext format for further text processing. here is my script and error msg:

> library(tidytext)
> tidyres  <- tidy(res)                                                         
> |Error in tidy.list(res) : No tidying method recognized for this list            
> | addition: Warning message:                                                   
> | sort(names(x)) == c("d", "u", "v") :                                         
> | object length is not a multiple of shorter object length 

Wondering if you had any suggestions. Thanks

**Comment by muschellij2** [comment]
Can you show me what res is?  I don't think this is going to really work as you want because I haven't done anything to make theses lists lend themselves to a tidytext format.  

As such, you have to do some manipulation yourself.  Also, you may want to be grabbing `res$content`, which may result in what you want.

**Comment by rpietro** [comment]
res came from your examples for the package. sure, I will look into $content. thanks
